version: '3.8'

services:
  dsp:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-dsp:latest
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
